version: '3'

networks:
    shared-services:
        external: true

services:
  go_mongo_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: go_mongo_api:latest
    restart: always
    env_file:
      - .env
    environment:
      - WATCH_FILES=${WATCH_FILES}
      - DEBUG=${DEBUG}
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app  # Mapear para o diretório correto dentro do contêiner
    networks:
      - shared-services