package gifts_seeder

import (
	"go_gift_list_api/src/infra/database/models"
	"log"

	"gorm.io/gorm"
)

func (g *GiftSeeder) createKitchenGifts(db *gorm.DB) {
	var kitchenCategoryID int64 = 2
	var kitchenGifts = []models.Gift{
		{
			Name:       "Panela de pressão",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "panela_pressao",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Panela de arroz",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "panela_arroz",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Grill",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "grill",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Jogo de copos",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "jogo_copos",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Jogo de pratos",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "jogo_pratos",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Depurador",
			CategoryID: kitchenCategoryID,
			Available:  -1,
			Image:      "depurador",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Cafeteira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "cafeteira",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Mixer",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "mixer",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Espremedor de frutas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "espremedor_frutas",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Misteira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "misteira",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Conjunto de panelas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "conjunto_panelas",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Conjunto de formas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "conjunto_formas",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Conjunto de vasilhas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "conjunto_vasilhas",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Jogo de faqueiro",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "conjunto_talheres_faqueiro",
			Quantity:   3,
			PriceGrade: 3,
		},
		{
			Name:       "Conjunto para cozinhar",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "conjunto_cozinhar",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Potes organizadores",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "potes_organizadores_cozinha",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Panos de prato",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "panos_prato",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Jarras",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "jarras",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Bandejas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "bandejas",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Copo medidor",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "copo_medidor",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Fruteira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "fruteira",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Tábua de corte",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "tabua_corte",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Porta papel toalha",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "porta_papel_toalha",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Abridor de latas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "abridor_latas",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Rodinho de pia",
			CategoryID: kitchenCategoryID,
			Available:  -1,
			Image:      "rodinho_pia",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Kit de lixeiras",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "kit_lixeiras",
			Quantity:   1,
			PriceGrade: 2,
		},
		{
			Name:       "Ralador",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "ralador",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Escorredor de louças",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "escorredor_loucas",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Queijeira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "queijeira",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Porta detergente e buchas",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "porta_dertegente_buchas",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Peneira de Arroz e Macarrão",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "peneira_arroz_macarrao",
			Quantity:   1,
			PriceGrade: 1,
		},
		{
			Name:       "Pipoqueira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "pipoqueira",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Batedeira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "batedeira",
			Quantity:   1,
			PriceGrade: 3,
		},
		{
			Name:       "Peneira",
			CategoryID: kitchenCategoryID,
			Available:  1,
			Image:      "peneira",
			Quantity:   1,
			PriceGrade: 1,
		},
	}

	for i := range kitchenGifts {
		err := db.Debug().Model(&models.Gift{}).Create(&kitchenGifts[i]).Error
		if err != nil {
			log.Fatalf("cannot seed kitchen gifts table: %v", err)
		}
	}
}
